services:

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            MSSQL_SA_PASSWORD: Mssql123
            ACCEPT_EULA: Y
        networks:
            lan:
                ipv4_address: 172.31.31.10
networks:
    lan:
        ipam:
            config:
                - subnet: 172.31.31.0/24