version: '2.2'

services:

    site:
        environment:
            - DATABASE_CONNECTION_STRING=Host=172.30.30.10;Port=5432;Pooling=true;User Id=postgres;Password=Postgres123
            - COOKIE_EXPIRES_IN_MINUTES=120
            - SECRET_JWT_KEY=utohWai7Iefa2loo7aeYeCo3HeWahpoKi5
        build: ./
        networks:
            lan:
                ipv4_address: 172.30.30.30
        ports:
            - "8090:80"

    pgadmin_web:
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        image: dpage/pgadmin4
        networks:
            lan:
                ipv4_address: 172.30.30.20

    database:
        environment:
            - POSTGRES_PASSWORD=Postgres123
        image: postgres
        networks:
            lan:
                ipv4_address: 172.30.30.10
  
networks:
    lan:
        ipam:
            config:
                - subnet: 172.30.30.0/24