version: '2.2'

services:



    db:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: Mysql123
        networks:
            lan:
                ipv4_address: 172.31.31.10
  
networks:
    lan:
        ipam:
            config:
                - subnet: 172.31.31.0/24