name: Build and Tests

on:
  push:
    branches:
      - 'none'
      - '!main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Tests Steps

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Use Node.JS 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        working-directory: ./Site
        run: pnpm install

      - name: Build Production Bundle
        working-directory: ./Site
        run: pnpm build:prod

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build and Test
        run: dotnet test