name: Build, Tests and Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Tests

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Use Node.JS 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        working-directory: ./Site
        run: pnpm install

      - name: Build Production Bundle
        working-directory: ./Site
        run: pnpm build:prod

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Run Db Migrations
        run: dotnet run --project Migrations/Migrations.csproj
        env:
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: cashflow-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: cashflow-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_459D85E33CF04D41A60F2A81084A2742 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C5705BE32DD4FA8AAED3423A527BAE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D2B70A867C6C4E84B3C3EBAE752E149E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cashfloweb'
          slot-name: 'Production'
          package: .
